### ISSUE TITLE
driver leaks bad $@

### ISSUE THREAD

**Issue by ralphiebaby** [ap/DBIx-Connector#51]
Whenever the driver can't require a specific driver subclass, it sets "$@" to report this. 
"$@" then leaks out, which creates a pitfall for any subsequent client code that is looking for errors.
in pre-0.42 DBIx::Connector, subsequent operations would usually clear the "$@" variable "accidentally" - but since 0.42, "$@" has been localised inside the try* subroutine's new TRY block which prevents them from accidentally unbuggering the global one.

I would recommend having the driver constructor unset $@ before returning, as this "error" resulting from falling back to the default driver is not something that calling code ever really needs to see (and if it needs to know its on the default driver, there are better ways to find out).

**Comment by ralphiebaby** [comment]
That sounds very plausible, I'll have a look at it today and get back to you.

**Comment by ap** [comment]
Thanks. I’ve pushed branch `fix-51` in case you want to take it for a spin. Do you have a test case?
